# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-30 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forums.Profile'),
        ),
    ]
