# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-01 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_auto_20170701_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_poster',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='topic',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
